version: 2
updates:
- package-ecosystem: bundler
  directory: "/blog"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  versioning-strategy: lockfile-only
- package-ecosystem: bundler
  directory: "/blog_src"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ffi
    versions:
    - 1.14.2
